//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// camd3000_Producer.rc에서 사용되고 있습니다.
//
#define IDI_ICON1                       102
#define IDI_ICON2                       104
#define IDD_TUNEIT_PRODUCTION           106
#define IDD_PMGROW_PRODUCTION           106
#define IDD_CAMD3000_PRODUCTION         106
#define IDC_EDIT_LOGVIEWER              1002
#define IDC_CONNECT                     1003
#define IDC_COMBO_COM_PORT              1004
#define IDC_COMBO_BAUARATE              1005
#define IDC_STATIC_APP_VERSION          1006
#define IDC_CLEAR                       1007
#define IDC_BTN_SETMDMUART              1008
#define IDC_BT_SEND_qflst               1009
#define IDC_BTN_FSEND                   1010
#define IDC_BTNF_BLE                    1011
#define IDC_BTNF_OBD                    1012
#define IDC_BTNF_TUNEIT_OBD             1013
#define IDC_BTN_FBP                     1014
#define IDC_BTNF_FILEDOWN               1015
#define IDC_BTNF_GET_INFO               1016
#define IDC_STATIC_OBD_VERSION          1017
#define IDC_STATIC_APP_VERSION2         1018
#define IDC_STATIC_EBP_VERSION          1018
#define IDC_STATIC_DB_VERSION           1019
#define IDC_EDIT_ATCOMMAND3             1020
#define IDC_STATIC_MDM_VERSION          1020
#define IDC_EDIT3                       1021
#define IDC_STATIC_ITEM                 1021
#define IDC_BTN_FILE_BROWSE3            1022
#define IDC_STATIC_ITEM2                1022
#define IDC_STATIC_UDR                  1022
#define IDC_BT_SEND_FILE3               1023
#define IDC_STATIC_ITEM3                1023
#define IDC_BT_SEND3                    1024
#define IDC_STATIC_ITEM4                1024
#define IDC_STATIC_LTE                  1024
#define IDC_EDIT_IMEI                   1025
#define IDC_STATIC_ITEM5                1025
#define IDC_STATIC_DB_VERSION2          1026
#define IDC_STATIC_ITEM6                1026
#define IDC_STATIC_ESIM                 1026
#define IDC_STATIC_CARCODE              1027
#define IDC_STATIC_ITEM7                1027
#define IDC_STATIC_IMEI                 1027
#define IDC_EDIT_MAC_ADDR               1028
#define IDC_STATIC_ITEM8                1028
#define IDC_STATIC_EBP                  1028
#define IDC_STATIC_CCID                 1028
#define IDC_EDIT_ATCOMMAND              1029
#define IDC_STATIC_ITEM9                1029
#define IDC_EDIT_CCID                   1030
#define IDC_STATIC_ITEM10               1030
#define IDC_STATIC_ACCEROMETER          1030
#define IDC_EDIT                        1031
#define IDC_STATIC_ITEM11               1031
#define IDC_BTN_FILE_BROWSE             1032
#define IDC_STATIC_CERT                 1032
#define IDC_STATIC_OBDCOMM              1032
#define IDC_BT_SEND_FILE                1033
#define IDC_BT_SEND                     1034
#define IDC_CHECK_FW_SKIP               1034
#define IDC_EDIT_ATCOMMAND1             1035
#define IDC_CHECK_FW_SKIP2              1035
#define IDC_CHECK_HW_SKIP               1035
#define IDC_EDIT1                       1036
#define IDC_STATIC_LED                  1036
#define IDC_BTN_FILE_BROWSE1            1037
#define IDC_CHECK_LED                   1037
#define IDC_BT_SEND_FILE1               1038
#define IDC_STATIC_SERIAL               1038
#define IDC_BT_SEND1                    1039
#define IDC_BUTTON_SAVE                 1039
#define IDC_EDIT_ATCOMMAND2             1040
#define IDC_BUTTON_GETINFO              1040
#define IDC_EDIT2                       1041
#define IDC_EDIT_SERIAL_NO              1041
#define IDC_BTN_FILE_BROWSE2            1042
#define IDC_BUTTON_GETINFO2             1042
#define IDC_BT_SEND_FILE2               1043
#define IDC_STATIC_LED2                 1043
#define IDC_BT_SEND2                    1044
#define IDC_EDIT_ATCOMMAND4             1045
#define IDC_EDIT4                       1046
#define IDC_BTN_FILE_BROWSE4            1047
#define IDC_BT_SEND_FILE4               1048
#define IDC_BT_SEND4                    1049
#define IDC_EDIT_ATCOMMAND5             1050
#define IDC_EDIT5                       1051
#define IDC_BTN_FILE_BROWSE5            1052
#define IDC_BT_SEND_FILE5               1053
#define IDC_BT_SEND5                    1054
#define IDC_EDIT_ATCOMMAND6             1055
#define IDC_EDIT6                       1056
#define IDC_BTN_FILE_BROWSE6            1057
#define IDC_BT_SEND_FILE6               1058
#define IDC_BT_SEND6                    1059
#define IDC_BTN_SETJIGMODE              1060
#define IDC_BT_SEND_QFDEL               1061
#define IDC_EDIT_VINCODE                1062
#define IDC_BTN_HW_TEST                 1063
#define IDC_EDIT_SERIAL_INDEX           1064
#define IDC_EDIT_SERIAL_MID             1065
#define IDC_BUTTON_SET_SN               1066
#define IDC_CHECK_BLE                   1067
#define IDC_BUTTON_SETJIGMODE           1068

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        105
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1040
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
